### ISSUE TITLE
Failing on certain usernames

### ISSUE THREAD

**Issue by zslabs** [weknowinc/gatsby-remark-twitter#12]
👋 Thanks for creating this! I'm getting some pretty weird results that just aren't adding up. I've checked the regex used in this library against a link like `https://twitter.com/Ana_M_Medina/status/1045730232743813121` (which it does correctly match), but when the library is actually performing the swaps, I noticed the debug and eventual widget output doesn't include it. It looks like it may have something to do with the multiple underscores in the username, but the regex seemed to correctly handle it, so I'm a bit 🤷‍♂️ on what's up here. Any thoughts would be greatly appreciated. Thanks!

cc @isaacs

**Comment by isaacs** [comment]
Yeah, what's happening is that it's converting the `_M_` into `<em>M</em>` because the `_` is getting markdowned.

**Comment by zslabs** [comment]
Ah interesting! Yep - you're 100% right. One thing I liked about https://www.gatsbyjs.org/packages/gatsby-remark-embed-video/ was being a bit more explicit with defining a video service provider, but I wonder if we'd run into a similar issue there if a video ID had an ID that matched something similar to what you mentioned; since this may be running too late in the remark chain.
