### ISSUE TITLE
Please bump version and re-publish from clean git checkout

### ISSUE THREAD

**Issue by isaacs** [weknowinc/gatsby-remark-twitter#17]
The 0.2.1 publish was done from 6f0e379bbe3abd6bc8c86ce63c3e4cc0833c7842, not ae436e9d4ad9296d1caf01726c25bb0365ed8fa9 (where the tag was set).  This can be verified by running `npm view @weknow/gatsby-remark-twitter@0.2.1 gitHead` and `git show-ref 0.2.1`.

This means that `0.2.1` on npm is not matching the `0.2.1` tag in git, which is confusing and weird.  https://github.com/weknowinc/gatsby-remark-twitter/pull/13#issuecomment-518373295

I recommend doing the following:

```bash
npm version patch
npm publish
git push origin master --follow-tags
```

And then the git tag and npm version will be in sync again.  Note that `npm version patch` will fail if the git environment is not clean, so it's the best way to ensure that the git tag and npm version are kept in sync.

**Comment by jmolivas** [comment]
Done, I followed the provided steps and the latest version now shows`0.2.3` since 0.2.2 was already tagged but not yet deployed.

**Comment by isaacs** [comment]
Thanks!
