### ISSUE TITLE
Does this work?

### ISSUE THREAD

**Issue by kentcdodds** [weknowinc/gatsby-remark-twitter#5]
I tried it and it doesn't seem to be working for me and I think the reason is that remark plugins are not capable of being async. I'm pretty sure they're supposed to run synchronously. I cannot find any documentation about async plugins if that is possible. Am I just missing something?

**Comment by BoyWithSilverWings** [comment]
Doesn't work for me either.

**Comment by isaacs** [comment]
Remark plugins can be async, but the tree walker functions can't be.  Fixed by #6.

**Comment by jmolivas** [comment]
Awesome @isaacs checking PR in a few, thanks @kentcdodds for reporting the issue
