### ISSUE TITLE
Add omit_script=t to the oembed call, and inject widgets.js script one time

### ISSUE THREAD

**Issue by isaacs** [weknowinc/gatsby-remark-twitter#8]
Otherwise posting a lot of tweets makes a lot of unnecessary `<script>` tags.

It looks like there's already code to do this in `gatsby-browser.js`, is that only for dev mode, or does it add the script in production as well?

**Comment by isaacs** [comment]
Addressed by #11, I believe, if not earlier.

**Comment by jmolivas** [comment]
Closing this since PR #11 was merged
