### ISSUE TITLE
Allow setting hide_thread=t in oembed call

### ISSUE THREAD

**Issue by isaacs** [weknowinc/gatsby-remark-twitter#9]
I want to be able to post a twitter thread as a series of urls, and if each one shows the one right above it, then it's really duplicative.

It'd be nice to put `hideThread: true` in the plugin options, and have it add `hide_thread=t` in the oembed query string to do this.  (Maybe this should be the default?)

**Comment by jmolivas** [comment]
Agree with making this the default and support the configuration `hideThread: true` to add `hide_thread=t`

**Comment by isaacs** [comment]
On #11, I made `hide_thread=t` the default, and you can set `hideThread: false` to _not_ hide the thread.  (Ie, it defaults to being hidden, not shown.)

**Comment by isaacs** [comment]
I do not like that twitter made their options reverse-boolean here.  Ie, set to true to not show the thing, and now we're defaulting to true, so you set it to false to not not show the thing...

**Comment by jmolivas** [comment]
Closing this one PR #11 merged
